server:
  port: 8080

spring:
  application:
    name: EXAMINATOR
    version: 0.0.1
    environment: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/examinator
      auto-index-creation: true      # Whether to create the Mongo database if it does not exist
    redis:
      port: 6379
      host: localhost
      database: 0

services:
  math:
    url: http://localhost:8081
  history:
      url: http://localhost:8082

management:
  probes:
    enabled: true
  endpoint:
    health:
      group:
        readiness:
          show-components: always
        liveness:
          show-components: always
        custom:
          show-components: always # Show the custom health check in the /actuator/health response
      show-details: always
      show-values: always
  endpoints:
    web:
      exposure:
        include: health,liveness,readiness,info,metrics,conditions,mappings,loggers,beans
        exclude: heapdump,threaddump,env


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
