server:
  port: 8080

spring:
  application:
    name: EXAMINATOR
    version: 0.0.1
    environment: dev
services:
  math:
    url: http://localhost:8081
  history:
      url: http://localhost:8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
