apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data: # all data is base 64 encoded, like echo -n "secretword" | base64
  uri: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9leGFtaW5hdG9y
