apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: examinator-hpa
  namespace: green
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-examinator-deployment
  minReplicas: 1
  maxReplicas: 10  # Adjust this value based on your requirements.
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75
      
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 75