apiVersion: v1
kind: ConfigMap
metadata:
  name: examinator-config
  namespace: green
data:
    server.port: "8080"
    spring.application.name: "EXAMINATOR"
    spring.application.version: "0.0.1"
    spring.application.environment: "green"
    services.math.url: "http://endpoint-math:8080"
    services.history.url: "http://endoint-history:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: history-config
  namespace: green
data:
    server.port: "8080"
    spring.application.name: "HISTORY"
    spring.application.version: "0.0.1"
    spring.application.environment: "green"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: green
  name: math-config
data:
  server.port: "8080"
  spring.application.name: "MATH"
  spring.application.version: "0.0.1"
  spring.application.environment: "green"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: green
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: green
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-examinator-deployment
  namespace: green
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-green-examinator
  template:
    metadata:
      labels:
        name: backend-green-examinator
    spec:
      containers:
        - name: exam-provider-container
          image: azspringapiacr3.azurecr.io/provider-examinator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: examinator-config
                  key: server.port
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                  configMapKeyRef:
                    name: examinator-config
                    key: spring.application.name
            - name: SPRING_APPLICATION_VERSION
              valueFrom:
                  configMapKeyRef:
                      name: examinator-config
                      key: spring.application.version

            - name: SPRING_APPLICATION_ENVIRONMENT
              valueFrom:
                  configMapKeyRef:
                      name: examinator-config
                      key: spring.application.environment
            - name: SERVICES_MATH_URL
              valueFrom:
                  configMapKeyRef:
                      name: examinator-config
                      key: services.math.url

            - name: SERVICES_HISTORY_URL
              valueFrom:
                  configMapKeyRef:
                      name: examinator-config
                      key: services.history.url

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-math-deployment
  namespace: green
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-green-math
  template:
    metadata:
      labels:
        name: backend-green-math
    spec:
      containers:
        - name: provider-math-container
          image: azspringapiacr3.azurecr.io/provider-math:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: math-config
                  key: server.port
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                  configMapKeyRef:
                      name: math-config
                      key: spring.application.name
            - name: SPRING_APPLICATION_VERSION
              valueFrom:
                  configMapKeyRef:
                      name: math-config
                      key: spring.application.version
            - name: SPRING_APPLICATION_ENVIRONMENT
              valueFrom:
                  configMapKeyRef:
                      name: math-config
                      key: spring.application.environment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-history-deployment
  namespace: green
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-green-history
  template:
    metadata:
      labels:
        name: backend-green-history
    spec:
      containers:
        - name: provider-history-container
          image: azspringapiacr3.azurecr.io/provider-history:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: history-config
                  key: server.port
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                  configMapKeyRef:
                      name: history-config
                      key: spring.application.name
            - name: SPRING_APPLICATION_VERSION
              valueFrom:
                  configMapKeyRef:
                      name: history-config
                      key: spring.application.version
            - name: SPRING_APPLICATION_ENVIRONMENT
              valueFrom:
                  configMapKeyRef:
                      name: history-config
                      key: spring.application.environment

---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-math
  namespace: green
spec:
  selector:
    name: backend-green-math
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-history
  namespace: green
spec:
  selector:
    name: backend-green-history
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-examinator
  namespace: green
spec:
  selector:
    name: backend-green-examinator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: endpoint-examinator-external
  namespace: green
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              service:
                name: endpoint-examinator
                port:
                  number: 80
            pathType: Exact