apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-examinator-hpa
  namespace: green
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-examinator-deployment
  minReplicas: 1
  maxReplicas: 10  # Adjust as needed
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
